version: "3"

volumes:
    mysql_data: {}
    mariadb_data: {}

services:
    # Primary services to use with this course
    oophp: &oophp
        image: dbwebb/courserepo:oophp
        volumes:
            - ".:/home/dbwebb/repo"
            - "/home/dbwebb/repo/bin"
            - "/home/dbwebb/repo/build"
            - "/home/dbwebb/repo/node_modules"
            - "/home/dbwebb/repo/vendor"
            - "./example/sql/inspect/my.cnf:/home/dbwebb/.my.cnf"

    cli:
        <<: *oophp

    server:
        <<: *oophp
        ports:
            - "1337:1337"



    # Add support for mysql and mariadb
    mariadb:
        container_name: mariadb
        image: mariadb/server:latest
        restart: always
        ports:
            - "13306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: pass
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./example/sql.d/mariadb:/docker-entrypoint-initdb.d
            - ./example/sql/inspect/mariadb_my.cnf:/root/.my.cnf

    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "13306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - mysql_data:/var/lib/mysql
            - ./example/sql.d/mysql:/docker-entrypoint-initdb.d
            - ./example/sql/inspect/mysql_my.cnf:/root/.my.cnf



    # Anax images to test various PHP versions
    php73:
        image: anax/dev:php73
        volumes: [ ".:/home/anax/repo" ]

    php73-apache:
        image: anax/dev:php73-apache
        ports: [ "10073:80" ]
        volumes: [ ".:/home/anax/repo" ]

    php72:
        image: anax/dev:php72
        volumes: [ ".:/home/anax/repo" ]

    php72-apache:
        image: anax/dev:php72-apache
        ports: [ "10072:80" ]
        volumes: [ ".:/home/anax/repo" ]
